<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>DevLauncherInstaller</AssemblyName>
    <RootNamespace>DevLauncherInstaller</RootNamespace>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishReadyToRunShowWarnings>false</PublishReadyToRunShowWarnings>
    <Optimize>true</Optimize>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <PathMap>$(MSBuildProjectDirectory)=/_</PathMap>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
    <Resource Include="icon.png" />
    <EmbeddedResource Include="payload.zip" Condition="Exists('payload.zip')" />
  </ItemGroup>

</Project>
